# https://github.com/catppuccin/tmux/blob/main/docs/reference/configuration.md#all-options-and-their-defaults
set -g @plugin 'catppuccin/tmux' # ** https://github.com/catppuccin/tmux
run '~/.config/tmux/plugins/tmux/catppuccin.tmux' # or where this file is located on your machine

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none
set -g @catppuccin_window_flags "text" # none, icon, or text

# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`
# run ~/.config/tmux/plugins/tmux/catppuccin.tmux # For TPM, instead use `

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
# set -g status-left ""
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
# Or, if using TPM, just run TPM
