## ** Status bar


# set # -a  is for append # -g global
# https://arcolinux.com/everything-you-need-to-know-about-tmux-status-bar/
# https://www.ditig.com/256-colors-cheat-sheet
set -g status-justify centre  # D(left)
# set -g status-style fg=colour136,bg=colour235
set -g status-style 'fg=#bdcbde bg=#333333'

set -g status-bg black
set -g status-fg colour35

set -g status-left-length 20  # 50 maximum length of the left component D(15)
set -g status-left-style default
set -g status-left "#[fg=green]#H #[fg=black]� #[fg=green,bright]#(uname -r)#[default]"
# set -g status-left "#[bg=colour35]💻#[fg=colour234,bold] #H #[bg=colour234,nobold]#[fg=colour35] [#S] $tmux_target_lower " # LLTVOld

set -g status-right-length 140
set -g status-right-style default
set -g status-right "#[fg=green,bg=default,bright]#{forecast} | #H"
set -ag status-right " #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d"
# set -g status-right '#[bg=colour234]#[fg=colour35]📈 #(cut -d " " -f 1-3 /proc/loadavg) #[bg=colour35]🕔 #[fg=colour234,bold]%H:%M ' # LLTVOld

# setw -g window-status-style fg=colour244
setw -g window-status-style fg=colour35
setw -g window-status-style bg=default

setw -g window-status-current-style fg=colour166
# setw -g window-status-current-style bg=default
setw -g window-status-current-style bold,bg=blue,fg=colour234
setw -g window-status-current-style bold,bg=colour35,fg=colour234 # LLTVOld
set -g window-status-activity-style bold,bg=colour234,fg=white
# set -g window-status-activity-style bg=blue,fg=black # LLTVOld


# ** tmux-mem-cpu-load
# set -g @plugin 'thewtex/tmux-mem-cpu-load'
# set -g status-interval 2
# # set -g status-left "#S #[fg=green,bg=black]#(tmux-mem-cpu-load -v --colors --interval 2)#[default]"
# set -g status-left-length 60
# set -g status-right '#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]'

# set-option -g window-status-format "#{pane_tty}:#W#F"
# # set -g window-status-format " #{?window_activity_flag, #[fg=colour231]#[blink],#[fg=colour245]}#{?window_bell_flag,#[fg=colour01]#[blink],#[fg=colour245]} #W "
# set -g window-status-style 'bg=colour232'
# set -g window-status-activity-style 'bg=colour232,fg=colour247,blink'
# set -g window-status-bell-style 'bg=colour232,fg=colour01,blink'
# set -g window-status-current-style 'bg=colour232,fg=colour09'

# https://medium.com/code-art/after-n-years-im-finally-using-tmux-in-such-an-elegant-way-8d2492d964db


# set -g window-status-format "#[fg=#bdcbde,bg=#333333] #I:#W #F "
# set -g window-status-current-format "#[fg=black,bg=#ffd700] #I:#W #F "
# set -g pane-active-border-style "fg=#ffd700"

# # ======================================================================
# # status line
# # ======================================================================
# set-option -g status-right-style 'fg=#ffd700 bg=#360000 bold'
# set-option -g status-left "#[fg=#ffd700,bg=#333333,bold] #S "
# set-option -g status-right " %Y-%m-%d %H:%M:%S "