# https://www.jondjones.com/tactics/productivity/windows-terminal-hacks-with-tmux-and-bash/
# ^+ ⬆️,⬇️ to create a new vertical pane
# ^+ ➡️⬅️ to create a new horizontal pane
# Alt + (⬆️➡️⬇️⬅️) to move between the shell
# ^ + `x to kill a terminal Window

unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

bind -n C-x killp

bind -n C-Left split-window -h
bind -n C-Right split-window -h
bind -n C-Down split-window -v
bind -n C-Up split-window -v

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind z source-file ~/.tmux.conf

set -g mouse on

# If you use the terminal a lot, the beeps and bells that are made whenever you make a mistake are VERY annoying. If you want to disable these annoyances
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

set-option -g status on
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-keys vi
set-option -g status-position bottom
set-option -g status-style fg=colour136,bg=colour235
set-option -g status-left-length 20
set-option -g status-left-style default
set-option -g status-left "#[fg=green]#H #[fg=black]� #[fg=green,bright]#(uname -r)#[default]"
set-option -g status-right-length 140
set-option -g status-right-style default
set-option -g status-right "#[fg=green,bg=default,bright]#{forecast} | #H"
set-option -ag status-right " #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d"
set-window-option -g window-status-style fg=colour244
set-window-option -g window-status-style bg=default
set-window-option -g window-status-current-style fg=colour166
set-window-option -g window-status-current-style bg=default


# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


set -g @plugin 'tmux-plugins/tpm'
# tmux-continuum: Continuum will automatically save you session state
# tmux-resurrect: Resurrect will restre your session state if your computer is reset
# tmux-sidebar: Press Cntrl + \ to get a menu to do all sorts of TMUX options. Handy so you do not need to remember loads of shortcuts
# tmux-weather: Adds weather information into the status bar
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'aaronpowell/tmux-weather'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'