# \u26a1 ⚡
console_title_template = '{{if .Root}} ⚡ {{end}}{{.Shell}} :: {{.UserName}} @ {{.HostName}}'
version = 2

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╭─'
    foreground = '#7a7a7a'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{ .Icon }} '
    foreground = '#458588'
    background = '#2f2f2f'
    type = 'os'
    style = 'diamond'

    [blocks.segments.options]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    template = ' <#7a7a7a> </>'
    foreground = '#ffff66'
    background = '#2f2f2f'
    type = 'root'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#282828'
    powerline_symbol = ''
    background = '#458588'
    type = 'path'
    style = 'powerline'

    [blocks.segments.options]
      style = 'full'

  [[blocks.segments]]
    template = '<#7a7a7a> </>{{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}<#E84855>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#2FDA4E>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ffeb3b'
    background = '#2f2f2f'
    type = 'git'
    style = 'diamond'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb3b{{ end }}', '{{ if gt .Ahead 0 }}#2EC4B6{{ end }}', '{{ if gt .Behind 0 }}#8A4FFF{{ end }}']

    [blocks.segments.options]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    trailing_diamond = ''
    foreground = '#fafafa'
    background = '#2f2f2f'
    type = 'text'
    style = 'diamond'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' ❮ '
    foreground = '#7a7a7a'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}<#fafafa>  </>'
    foreground = '#FFCE5C'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.options]
      style = 'roundrock'
      threshold = 500.0

  [[blocks.segments]]
    template = '  {{ if gt .Code 0 }}{{ .Code }}{{ end }} '
    foreground = '#9FD356'
    type = 'exit'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#E84855{{ end }}']

    [blocks.segments.options]
      always_enabled = true

  [[blocks.segments]]
    leading_diamond = ''
    foreground = '#fafafa'
    background = '#2f2f2f'
    type = 'text'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}<#7a7a7a> </>'
    foreground = '#6CA35E'
    background = '#2f2f2f'
    type = 'node'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}<#7a7a7a> </>'
    foreground = '#96E072'
    background = '#2f2f2f'
    type = 'python'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}<#7a7a7a> </>'
    foreground = '#3891A6'
    background = '#2f2f2f'
    type = 'dotnet'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .CurrentDate | date .Format }}'
    foreground = '#26C6DA'
    background = '#2f2f2f'
    type = 'time'
    style = 'diamond'

    [blocks.segments.options]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─ '
    foreground = '#7a7a7a'
    type = 'text'
    style = 'plain'
