"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = "\uf0ef "

[azure]
symbol = "\ue754 "

[battery]
full_symbol = "\U000f0079 "
charging_symbol = "\U000f0084 "
discharging_symbol = "\U000f0083 "
unknown_symbol = "\U000f0091 "
empty_symbol = "\U000f008e "

[buf]
symbol = "\uf49d "

[bun]
symbol = "\ue76f "

[c]
symbol = "\ue61e "

[cpp]
symbol = "\ue61d "

[cmake]
symbol = "\ue794 "

[cobol]
symbol = "\uf013 "

[conda]
symbol = "\ue715 "

[container]
symbol = "\uf4b7 "

[crystal]
symbol = "\ue62f "

[dart]
symbol = "\ue64c "

[deno]
symbol = "\ue7c0 "

[direnv]
symbol = "\ue613 "

[directory]
read_only = " \U000f033e"

[docker_context]
symbol = "\uf308 "

[dotnet]
symbol = "\ue77f "

[elixir]
symbol = "\ue62d "

[elm]
symbol = "\ue62c "

[erlang]
symbol = "\uf23f "

[fennel]
symbol = "\ue6af "

[fortran]
symbol = "\ue7de "

[fossil_branch]
symbol = "\uf418 "

[gcloud]
symbol = "\U000f11f6 "

[gleam]
symbol = "\uf005 "

[git_branch]
symbol = "\uf418 "

[git_commit]
tag_symbol = ' \uf412 '

[golang]
symbol = "\ue627 "

[gradle]
symbol = "\ue660 "

[guix_shell]
symbol = "\uf325 "

[haskell]
symbol = "\ue777 "

[haxe]
symbol = "\ue666 "

[helm]
symbol = "\ue7fb "

[hg_branch]
symbol = "\uf418 "

[hostname]
ssh_symbol = "\ueb01 "

[java]
symbol = "\ue738 "

[julia]
symbol = "\ue624 "

[kotlin]
symbol = "\ue634 "

[kubernetes]
symbol = "\U000f10fe "

[lua]
symbol = "\ue620 "

[maven]
symbol = "\ue674 "

[memory_usage]
symbol = "\U000f035b "

[meson]
symbol = "\U000f0537 "

[mojo]
symbol = "\U000f0238 "

[nats]
symbol = "\uf0e0 "

[netns]
symbol = "\U000f06f3 "

[nim]
symbol = "\ue677 "

[nix_shell]
symbol = "\uf313 "

[nodejs]
symbol = "\ue718 "

[ocaml]
symbol = "\ue67a "

[odin]
symbol = "\U000f07e2 "

[opa]
symbol = "\uf132 "

[openstack]
symbol = "\ue856 "

[os.symbols]
AIX = "\ue8cc "
AlmaLinux = "\uf31d "
Alpaquita = "\ueaa2 "
Alpine = "\uf300 "
ALTLinux = "\uf31a "
Amazon = "\uf270 "
Android = "\uf17b "
AOSC = "\uf301 "
Arch = "\uf303 "
Artix = "\uf31f "
Bluefin = "\uf31a "
CachyOS = "\uf303 "
CentOS = "\uf304 "
Debian = "\uf306 "
DragonFly = "\ue28e "
Elementary = "\uf309 "
Emscripten = "\ue6a1 "
EndeavourOS = "\uf322 "
Fedora = "\uf30a "
FreeBSD = "\uf30c "
Garuda = "\uf337 "
Gentoo = "\uf30d "
HardenedBSD = "\U000f078c "
Illumos = "\uf326 "
InstantOS = "\uf31a "
Ios = "\U000f0037 "
Kali = "\uf327 "
Linux = "\uf31a "
Mabox = "\ueb29 "
Macos = "\uf302 "
Manjaro = "\uf312 "
Mariner = "\uf1cd "
MidnightBSD = "\uf186 "
Mint = "\uf30e "
NetBSD = "\uf024 "
NixOS = "\uf313 "
Nobara = "\uf380 "
OpenBSD = "\uf328 "
OpenCloudOS = "\uf31a "
openEuler = "\uf31a "
openSUSE = "\uf314 "
OracleLinux = "\U000f0ea1 "
PikaOS = "\uf31a "
Pop = "\uf32a "
Raspbian = "\uf315 "
Redhat = "\U000f111b "
RedHatEnterprise = "\U000f111b "
Redox = "\U000f0018 "
RockyLinux = "\uf32b "
Solus = "\uf32d "
SUSE = "\uf314 "
Ubuntu = "\uf31b "
Ultramarine = "\uf31a "
Unknown = "\uf22d "
Uos = "\uf321 "
Void = "\uf32e "
Windows = "\U000f0372 "
Zorin = "\uf32f "

[package]
symbol = "\U000f03d7 "

[perl]
symbol = "\ue67e "

[php]
symbol = "\ue608 "

[pijul_channel]
symbol = "\uf418 "

[pixi]
symbol = "\U000f03d7 "

[pulumi]
symbol = "\ue873 "

[purescript]
symbol = "\ue630 "

[python]
symbol = "\ue235 "

[raku]
symbol = "\U000f158a "

[red]
symbol = "\U000f137c "

[rlang]
symbol = "\U000f07d4 "

[ruby]
symbol = "\ue791 "

[rust]
symbol = "\U000f1617 "

[scala]
symbol = "\ue737 "

[shlvl]
symbol = "\U000f0e4d "

[singularity]
symbol = "\uf4b7 "

[solidity]
symbol = "\ue8a6 "

[spack]
symbol = "\ue8aa "

[status]
symbol = "\uf467 "

[sudo]
symbol = "\uef01 "

[swift]
symbol = "\ue755 "

[terraform]
symbol = "\ue69a "

[vlang]
symbol = "\ue6ac "

[typst]
symbol = "\uf37f "

[vagrant]
symbol = "\ue8d0 "

[xmake]
symbol = "\ue794 "

[zig]
symbol = "\ue6a9 "
